### ISSUE TITLE
uninstall doesn't remove fields

### ISSUE THREAD

**Issue by h-c-c** [woolman/genderselfidentify#1]
Hi, I'm having an issue where uninstallation doesn't remove the field User Entered Gender from the contact record.  Can you help?

Thank you

**Comment by colemanw** [comment]
I would call this "by design" - deleting data from CiviCRM is not something you want to "just happen." If you are done with this extension and want the custom field gone, just delete it the normal way.

**Comment by h-c-c** [comment]
Right, except your custom data field is hidden from the list.  So there is no "normal way" to remove it. 

There are plenty of warning in CiviCRM about the deletion of data when an extension is removed.  If a user removes an extension, they naturally must understand they want to remove data. 

If you're not including cleanup scripts, then please make sure you have users consent about unremovable data fields.

**Comment by colemanw** [comment]
Ah, you're right, it's a reserved group so doesn't show up in the list.
This ought to fix it: a14617b
This un-reserves and disables the custom group on extension disable, which will get rid of the field from the UI, but reveal it to the admin screen so you can easily delete it.
