### ISSUE TITLE
randomly inserts numeral in Other field

### ISSUE THREAD

**Issue by h-c-c** [woolman/genderselfidentify#2]
The genderselfidentiy extension, for some users, inserts the civi numerical gender code in the Other field. I  have personally filled out forms for accounts that this has happened to.  Nothing was filled in in the Other field.

![screen shot 2015-10-31 at 1 32 43 pm](https://cloud.githubusercontent.com/assets/5252344/10864963/0c54fc12-7fd4-11e5-9428-db2c2b1bf556.png)

**Comment by colemanw** [comment]
Pls ensure you are using the latest version of this extension - something similar was fixed in 1.2.

**Comment by colemanw** [comment]
Is this still an issue with the latest version? If so can you please provide exact steps to reproduce the bug? What form were you using? What type of user were you logged in as? Were you creating or updating a contact? What was entered in the gender field?

**Comment by colemanw** [comment]
I would be happy to help resolve this but no response from @h-c-c so closing.
