### ISSUE TITLE
String offset access with curling braces deprecated in PHP 7.4

### ISSUE THREAD

**Issue by cpbruton** [woolman/genderselfidentify#6]
Since I installed the gender self-identity extension I am getting the following warning in my cron job output:

Deprecated: Array and string offset access syntax with curly braces is deprecated in /.../wp-content/uploads/civicrm/ext/org.woolman.genderselfidentify/genderselfidentify.civix.php on line 150

It seems this method of accessing arrays and strings was [deprecated in PHP 7.4](https://wiki.php.net/rfc/deprecate_curly_braces_array_access).

The line in question: https://github.com/woolman/genderselfidentify/blob/cf3635a070da948f2be9c7e9e62b75f0e8c275ec/genderselfidentify.civix.php#L150

I'm not familiar with CiviCRM extensions, but it seems this is some boilerplate code related to auto updates? The actual fix seems trivial - change the braces { } to brackets [ ] on line 150.

**Comment by colemanw** [comment]
Fixed and released a new version

**Comment by cpbruton** [comment]
Thanks for the quick fix! We installed the update last week and I'm no longer seeing the warning.
